FROM python:3.12-slim

WORKDIR /app

COPY server.py /app
COPY text_to_speech.proto /app
COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. text_to_speech.proto

EXPOSE 50051

CMD ["python", "server.py"]
