# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text_to_speech.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'text_to_speech.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14text_to_speech.proto\x12\x0etext_to_speech\"&\n\x10NarrationRequest\x12\x12\n\ntext_input\x18\x01 \x01(\t\"B\n\x11NarrationResponse\x12\x12\n\naudio_file\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0b\n\x03wpm\x18\x03 \x01(\x02\x32h\n\x0cTextToSpeech\x12X\n\x11GenerateNarration\x12 .text_to_speech.NarrationRequest\x1a!.text_to_speech.NarrationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_to_speech_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NARRATIONREQUEST']._serialized_start=40
  _globals['_NARRATIONREQUEST']._serialized_end=78
  _globals['_NARRATIONRESPONSE']._serialized_start=80
  _globals['_NARRATIONRESPONSE']._serialized_end=146
  _globals['_TEXTTOSPEECH']._serialized_start=148
  _globals['_TEXTTOSPEECH']._serialized_end=252
# @@protoc_insertion_point(module_scope)
